[package]
name = "emumerate"
version = "0.1.0"
authors = ["Eric <ekiesow@mail.csuchico.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
